export const GROUP_PATH_DELIMITER = '/';
export const SPEC_VERSION_SURVEY = 4;
export const SPEC_VERSION_SUBMISSION = 3;
export const SPEC_VERSION_SCRIPT = 2;
export const SPEC_VERSION_GROUP = 2;
export const ASELECT_MAX_ITEMS_TOBE_VSELECT = 15;
export const ARCHIVE_REASONS = ['TEST_DATA', 'INCORRECT_DATA', 'EQUIPMENT_ERROR', 'USER_ERROR', 'RESUBMIT', 'OTHER'];
export const MAPBOX_ACCESS_TOKEN = 'pk.eyJ1Ijoib3Vyc2NpbGxjIiwiYSI6ImNsdmdzcTA0azB6N2YybG1nY3I3azNtOTIifQ.ViY_6XxZ_sOLtbB_rh8m0g';
