
pages:
  stage: deploy
  script:
    - git clone https://gitlab.com/our-sci/our-sci-pwa.wiki
    - mkdir .public
    - rm -rf public
    - cp -r our-sci-pwa.wiki/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
