
variables:
  GIT_DEPTH: "3"

image:
  name: "node:15"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'

.cache-policy:
  cache:
    # cache per branch
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - client/node_modules/
      - node_modules/

.pull-cache-only:
  extends: .cache-policy
  cache:
    # pull and use the cache, but do not update it
    policy: pull

stages:
  - install
  - lint
  - test

lerna bootstrap:
  extends: .cache-policy
  stage: install
  script:
    - yarn
    - yarn lerna bootstrap
  
lint:
  extends: .pull-cache-only
  stage: lint
  script:
    - yarn client:lint
  needs:
    - lerna bootstrap

test:
  extends: .pull-cache-only
  stage: test
  script:
    - yarn client:test
  needs:
    - lerna bootstrap
