version: "3.7"

services:
  app:
    image: ${IMAGE_APP}
    environment:
      - PATH_PREFIX=
      - BCRYPT_ROUNDS=12
      - ADMIN_USERNAME=root
      - ADMIN_EMAIL=admin@our-sci.net
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PORT=${PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_DEFAULT_SENDER=${SMTP_DEFAULT_SENDER}
      - FARMOS_CALLBACK_KEY=${FARMOS_CALLBACK_KEY}
      - ELASTIC_ENABLE_LOGGING=${ELASTIC_ENABLE_LOGGING}
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME}
      - ELASTIC_CLOUD_ID=${ELASTIC_CLOUD_ID}
      - ELASTIC_AUTH_USERNAME=${ELASTIC_AUTH_USERNAME}
      - ELASTIC_AUTH_PASSWORD=${ELASTIC_AUTH_PASSWORD}
      - UNLEASH_URL=${UNLEASH_URL}
      - UNLEASH_INSTANCE_ID=${UNLEASH_INSTANCE_ID}
      - UNLEASH_APP_NAME=${UNLEASH_APP_NAME}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - FARMOS_AGGREGATOR_URL=${FARMOS_AGGREGATOR_URL}
      - FARMOS_AGGREGATOR_APIKEY=${FARMOS_AGGREGATOR_APIKEY}
      - FARMOS_CREATE_KEY=${FARMOS_CREATE_KEY}
    network_mode: host
    restart: always
